### ISSUE TITLE
better autolock

### ISSUE THREAD

**Issue by hermitdemschoenenleben** [hermitdemschoenenleben/linien#127]
# new autolock
* [x] robust.py: N_spectra_required dynamic?
* [ ] reorganize LinienLogic etc?
* [x] "determine signal offset" --> autolock doesn't work
* [x] UI for "collecting spectra"
* [x] UI for autolock method selection
* [x] ~~FPGA_DELAY_LOCK_POSITION_FINDER: Is this in clock cycles or in writing_data_now cycles?~~ writing_data_now cycles
* [x] ~~for better handling of jitter: `wait_for` between peaks should not just be detected in the first spectrum but in all of them~~
* [x[ ~~new autolock CPU: remove .9 arbitrary length scale tolerance factor~~
* [x] new autolock CPU: enforce max_N_instructions
* [x] Implement detection of jitter-level that decides which method to use
  * [x] Write test
* [x] ~~In addition to sumdiff-filtering: lowpass / bandpass filter only for ramp that switches to normal operation when in lock?~~ doesn't make sense

# old stuff
* [x] ~~how many points are actually recorded by scope depending on scan frequency? Is 8191 (max_delay, etc.) required at all?~~ irrelevant
* [x]~~ fetch_quadratures should be set automatically when locking. Forgetting to set it means no data is displayed because data count is wrong~~
* [x] Implement fast autolock for low jitter
  * [x] should be able to lock to any point of the ramp (not just 0)
  * [x] when using manual lock: set target point ~~to 0~~ to N/2
  * [x] Write test for it
* [x] scope: `written_data <= adc_a_dat ;` means that only channel A is used. Implement the same for dual channel?
* [x] robust autolock should also work with PFD transition
* [x] Reduce the number of data points transmitted
* [x] don't transmit quadratures
* [x] don't try to center the view in the end
* [x] final_zoom_factor should be bigger
* [x] DynamicDelay has to have reasonable max_delay
* [x] **robust autolock may only trigger if ramp is going up**
* [x] when programming autolock FPGA, implement a mechanism that
  * [x] first writes instructions and takes care that while doing so, autolock is not active
  * [x] autolock activation is requested
  * [x] autolock doesn't really start until at_start==1
* [x] Integrate AutolockFPGA into Linien Gateware
  * [x] write test for integration with PID
  * [x] is final_wait_time integrated in FPGA?
* [x] new autolock CPU has to write registers of AutolockFPGA
  * [x] consider FPGA_DELAY_LOCK_POSITION_FINDER
* [x] new autolock CPU: detect SpectrumUncorrelatedException
* [x] new autolock CPU: y shift such that initial line always has + and - peak. Is this really needed?
* [x] Keep old autolock algorithm or remove it completely?
* [x] auto_offset
* [x] watch_lock

**Comment by bleykauf** [comment]
+1 for JOKARUS method.

**Comment by hermitdemschoenenleben** [comment]
problem is that it only works well for isolated lines, not if there are adjacent ones. Another alternative is some kind of "peak counter" that runs directly on the FPGA and stops the ramp according to a description of the lock point that was given by the CPU. Not sure if this works in practice, but in theory it would be the best solution, I think
