### ISSUE TITLE
How to compile linien to make new executable ?

### ISSUE THREAD

**Issue by mihatoma** [hermitdemschoenenleben/linien#131]
Hi guys,

The software is amazing and well written. 
I'm a beginner in Python and I'm trying to understand the code.

I wanted to do some small tweaks with it - but I have one main problem.

How do I compile it?

I've tried several options including pyinstaller make.py from the root folder or linien.py from the gateware folder, but I receive several errors.
Commands:
pyinstaller --onefile make.py
pyinstaller --onefile linien.py

I've also tried --onedir from the anaconda prompt with or without the tensorflow env activated. 
Is there anything specific that needs addressing?

Thanks,
Best regards,
Mike

**Comment by hermitdemschoenenleben** [comment]
Thank you :)

`make.py` is used for building the FPGA gateware. For the GUI application `scripts/build_standalone_client.sh` is used which calls `pyinstaller client.spec`. Note that you should create a linien/VERSION file before, containing a version number. When your client connects to RedPitaya, it expects the linien server running there to have the same version number (current one is `0.2.3`). As I'm currently working on some bigger changes in the repo that are not yet tested, I'd recommend that you go back to commit `8b0259a` of the repo if you experience any problems.

For developing it may be useful to use `dev` as version number. This means that the client uploads the contents the server folder and uses it to start the server. For this, you need to have the built FPGA bitstream at `linien/server/linien.bin`. You can either use `scripts/build_gateware.py` to build it (using Vivado toolchain) or use the version from the latest linien-server python package: https://pypi.org/project/linien-server/#history
