### ISSUE TITLE
Improve controls for ramp amplitude

### ISSUE THREAD

**Issue by aisichenko** [hermitdemschoenenleben/linien#152]
Hello, I've searched but could not find it: is there a control of the ramp amplitude? I see that there is a ramp frequency input. It would be very useful to add amplitude control. Thanks!

**Comment by hermitdemschoenenleben** [comment]
@aisichenko ramp amplitude is controlled via "zoom" in the top left of the window. I should probably rename this control in order to state more clearly that this actually controls ramp amplitude and not only the data that is displayed

**Comment by aisichenko** [comment]
I see the ramp amplitude changing, thanks! And yes, I agree, that would make it more clear. Perhaps two options: one that is just zoom, another that is "enable ramp manual control" that will have options for ramp freq, ramp amplitude, and ramp offset. Thanks again
