### ISSUE TITLE
Ramp signal display information

### ISSUE THREAD

**Issue by aisichenko** [hermitdemschoenenleben/linien#158]
Hello,

Thanks for your great work! I was wondering if we can include a display of the ramp status. Specifically the ramp amplitude or Vpp and the ramp DC offset. 

This is useful for locking using an AOM system, where we'd like to make sure that we are not applying too much voltage to our VCO control port.

Thanks!

**Comment by hermitdemschoenenleben** [comment]
Hi,

a few days ago I pushed this to the master branch:
![Bildschirmfoto von 2021-03-03 21-35-52](https://user-images.githubusercontent.com/16289650/109868911-884b2080-7c68-11eb-82ea-4c46d17b1fd5.png)
I'll try to release a new version of Linien next week including this change, I'll notify you then

**Comment by hermitdemschoenenleben** [comment]
@aisichenko one thing you should keep in mind: when starting Linien server on RedPitaya, the FPGA image is re-flashed. Then, there is a short period of time before the client has set all parameters, i.e. the output may be in an undefined state for a second or so --> it's best to wait until everything is completely running before connecting your sensitive device

**Comment by aisichenko** [comment]
Understood. Thanks!!

**Comment by hermitdemschoenenleben** [comment]
@aisichenko I just uploaded 0.4.0 (and the bugfix release 0.4.1) which includes the ramp signal display. I also implemented recording PSD of error signal (#124) when the laser is locked - if you have any thoughts on this, your comments are more than welcome!
