### ISSUE TITLE
Jitter tolerant locking mode does not work

### ISSUE THREAD

**Issue by bleykauf** [hermitdemschoenenleben/linien#163]
If I use jitter tolerant locking mode, the following happens:

![jitter_tolerant](https://user-images.githubusercontent.com/6155893/110765184-39971b00-8254-11eb-826e-f71bc206a71f.PNG)

The error signal is still live, i.e. the ramp is running. Sometimes the spectroscopy signal turns blue for a split second and the ramp is visible for a short time (in red).

**Comment by hermitdemschoenenleben** [comment]
@bleykauf does it work when "check lock" / "watch lock" is disabled? If not: could you export the data of the spectrum (--> view tab), then I can write a test case for it

**Comment by bleykauf** [comment]
Now works with v0.4.2.
