### ISSUE TITLE
Rework requirement files and install_requires

### ISSUE THREAD

**Issue by bleykauf** [hermitdemschoenenleben/linien#183]
I think the installallation requirements for linien are too stringent, i.e. `install_requires` often pins very specific versions of packages. This makes it hard to install linien alongside other programs inside the same environment.

There is an important distiction between requirement files and install_requirements (https://packaging.python.org/discussions/install-requires-vs-requirements/), i.e. install_require in `setup.py` should be abstract and allow for a wide range of versions, whereas the `requirements.txt` should be concrete, i.e. pin certain versions for repeatable installations and for building the executables.

I therefore propose:

1. Pin specific versions for all packages defined in the `requirements_*.txt` files
2. Use these files in the github workflows instead of defining another set of requirements in the workflow yml files (I don't really know how this would be done, do you @hermitdemschoenenleben?)
3. Define abstract requirements directly in the `setup_*.py` files

We have to identify all (un-) suitable versions for the abstract requirements: the only restriction that I can think of that might break things is rpyc >= 5.0.0 as is already defined in `setup_server.py`, see #145.

**Comment by hermitdemschoenenleben** [comment]
Sounds great! 

To 2.: I think inside the `.yml` runner file instead of creating a `requirements.txt` using
```
run: printf "altgraph==0.17\nappdirs==1.4.4\nbcrypt==3.2.0\ncffi==1.14.2\nclick==7.1.2\ncryptography==3.0\nfuture==0.18.2\nnumpy==1.19.1\nparamiko==2.7.1\npefile==2019.4.18\nplumbum==1.6.9\npycparser==2.20\nPyNaCl==1.4.0\nPyQt5==5.15.0\nPyQt5-sip==12.8.0\npyqtgraph==0.11.0\npywin32-ctypes==0.2.0\nrpyc==4.1.5\nscipy==1.4.1\nsix==1.15.0\nuuid==1.30" > requirements.txt
```
you can just copy the file from the repo that was checked out a few lines above
