### ISSUE TITLE
PyRedPitaya is missing as requirement.

### ISSUE THREAD

**Issue by bleykauf** [hermitdemschoenenleben/linien#218]

**Comment by hermitdemschoenenleben** [comment]
the original PyRedPitaya is incompatible with Python 3. I forked it and ported it to python3 (with minor adjustments): https://github.com/hermitdemschoenenleben/pyrp3

This version doesn't have a proper package, though. As Linien server has some non-python requirements anyway that are installed via `linien_install_requirements`, I just check out the git repo and install it manually.

--> the proper way would be to make pyrp3 a python package and depend on it in `linien-server`. But honestly, as we have to keep `linien_install_requirements` anyway, I'm fine with keeping the current situation
