### ISSUE TITLE
Distorted modulation signal

### ISSUE THREAD

**Issue by jutiszma** [hermitdemschoenenleben/linien#227]
![tek00005](https://user-images.githubusercontent.com/87863283/146550327-ef0d0c02-58b2-40aa-9be5-4c8c891bfcba.png)

Looking at the modulation signal (fast out one) without the sweep and control signal (fast out two) at low frequencies (500kHz) on an oscilloscope, I can observe additional amplitude modulation on the rising slope.

**Comment by bleykauf** [comment]
To narrow down the issue: does this behaviour persist when going to higher
frequencies?

jutiszma ***@***.***> schrieb am Fr., 17. Dez. 2021, 14:43:

**Comment by jutiszma** [comment]
Going to higher frequencies (5MHz) the modulation seems to extend over the whole period
![tek00000](https://user-images.githubusercontent.com/87863283/146556050-6eb81181-b24e-47bb-af48-fb422541807e.png)
.

**Comment by bleykauf** [comment]
Just tested with my RedPitaya and could not reproduce the issue:

![PXL_20220112_140019998 MP](https://user-images.githubusercontent.com/6155893/149155108-f149b541-338d-41fc-b043-d36867723f7e.jpg)

I would assume that this is rather a problem with your specific device.
