### ISSUE TITLE
Sweep Frequency still there during locking!

### ISSUE THREAD

**Issue by AaronStra** [hermitdemschoenenleben/linien#94]
During lock the sweeping frequency is still applied to the control output.
Data with sweeping frequency of 30 Hz.
![image](https://user-images.githubusercontent.com/28979330/86330368-e0e49c80-bc47-11ea-8247-d9b57f93def7.png)

**Comment by hermitdemschoenenleben** [comment]
issue is fixed in latest release (0.2.2)
